Add transparent mode
luisiacc/gruvbox-baby pull request #9
Opened 2022-02-12 18:54 UTC by crzdg

Hi all!

Sorry for the multiple commits, tried this out with online editor and PackerUpdate. Please squash when merge!

I was setting up my tmux to change colors for in-/active panes.
In order to make nvims background color adjust to the pane background some colors need to be transparent (none).
In this PR I added the option to select "transparent" alongside "medium", "dark".

I already have found some flaws with this on lualine for the section: "diagnostics", "mode" and "location". Also a custom section which is based on text (most right) doesn't seem to have problems with the none-color. See screenshot.
Maybe you have an idea how to change those colors back to the theme ones. I think some of the colors in the `theme` file needs to be adjusted to the introduced `palette.background_colored` variable.

![image](https://user-images.githubusercontent.com/4175183/153724412-993cdfeb-f079-42eb-8a84-acb9d003b06e.png)

2022-02-12 20:18 UTC, luisiacc reviewed
Thank you for this!

2022-02-12 20:18 UTC, luisiacc commented on lua/gruvbox-baby/colors.lua
> +
Seems like this is not used, could you remove it? Then I can merge it.

2022-02-12 20:19 UTC, luisiacc commented
I saw something about lualine inactive sections on the tokyonight theme: https://github.com/folke/tokyonight.nvim/blob/main/lua/tokyonight/theme.lua#L464

2022-02-12 21:26 UTC, luisiacc requested changes

2022-02-12 21:26 UTC, luisiacc commented on lua/gruvbox-baby/theme.lua
> +    local inactive = { style = "underline", bg = c.background_colored, fg = c.foreground, sp = c.foreground }
Could you change `background_colored` here and remove those 2 `background_colored` fields from the palette? I feel they don't serve a purpose

2022-02-12 21:26 UTC, luisiacc commented on lua/gruvbox-baby/theme.lua
> +      theme.defer["lualine_" .. section .. "_inactive"] = inactive
This will cause an error because `theme.defer` does not exists. you have to create a `theme.defer = {}` before the `if` condition to make it work.

2022-02-12 23:45 UTC, crzdg commented
Hey

I figured out how to provide a theme to `Lualine`. I will prepare a branch on my fork and adjust the PR.

2022-02-14 15:11 UTC, luisiacc approved these changes
This looks great! Thank you, I'll merge it when I get to my computer.

2022-02-14 15:56 UTC, merged